on:
  push:
    branches: [main]

name: Deploy SAM Template

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: SAM Validate
        run: |
          sam validate --template-file template.yaml
      - name: SAM Build
        run: |
          sam build
      - name: SAM Package
        run: |
          sam package --template-file template.yaml --s3-bucket ${{ secrets.S3BUCKET }} --s3-prefix aws-serverless-blogs --output-template-file template.updated.yaml        
        working-directory: .aws-sam/build
      - name: SAM Deploy
        run: |
          sam deploy --template-file template.updated.yaml \
            --stack-name aws-serverless-blogs \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --region ap-southeast-2 \
            --no-fail-on-empty-changeset \
            --parameter-overrides WebhookUrl=${{ secrets.WEBHOOKURL }}
        working-directory: .aws-sam/build